-- ============================================================================
-- 20260905090000_phase4_training_read_model.sql
-- Phase 4: the training read model.
--
-- WHAT THIS IS, AND WHAT IT DELIBERATELY IS NOT
--
-- This is a read layer over the canonical model, not a second pipeline. Every
-- function here reads the v_* views and aggregates at query time. Nothing is
-- materialised, no derived metric row is written, and no rollup table is
-- created: CLAUDE.md section 6 puts derived metrics and weekly/monthly rollup
-- tables out of scope, and v2 section 9.5 says to aggregate from the canonical
-- series on read until a real query is measurably slow. When Phase 5 brings
-- metric_daily and the rollup queue, these functions are what it replaces.
--
-- SECURITY
--
-- Every function is SECURITY INVOKER (the default) and reads only the v_*
-- views, which are themselves security_invoker. Row level security therefore
-- applies as the calling user, exactly as it does for a direct table read.
-- None of them takes a user id: a caller cannot ask for another user's data,
-- because there is no parameter with which to ask.
--
-- AGGREGATION SEMANTICS, STATED EXPLICITLY
--
-- volume_kg is generated by the database as COALESCE(weight_kg,0) * COALESCE(reps,0).
-- For a set that carries no load (a carry, a plank, a distance interval) that
-- evaluates to zero, which is arithmetically right and analytically misleading:
-- summing it silently mixes "no load" with "zero load". So every volume
-- aggregate below counts ONLY sets where weight_kg IS NOT NULL AND reps IS NOT
-- NULL, and reports the remaining sets separately as non_volume_sets. A period
-- with sets but no loaded sets returns volume NULL, not 0, so a chart can show
-- a gap rather than fabricate a floor.
--
-- Weeks are ISO weeks over local_date, which v2 section 8.1 already defines as
-- the date the user experienced. No timezone maths happens here.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Supporting indexes for the aggregations below.
-- ---------------------------------------------------------------------------

create index if not exists strength_exercises_user_definition_idx
  on public.strength_exercises (user_id, exercise_definition_id);

create index if not exists strength_sets_user_active_idx
  on public.strength_sets (user_id) where retired_at is null;

-- ---------------------------------------------------------------------------
-- Overview: the headline numbers on the dashboard.
-- ---------------------------------------------------------------------------

create or replace function public.training_overview()
returns table (
  total_workouts        bigint,
  total_exercise_slots  bigint,
  distinct_exercises    bigint,
  total_sets            bigint,
  volume_sets           bigint,
  non_volume_sets       bigint,
  total_volume_kg       numeric,
  first_workout_date    date,
  last_workout_date     date,
  workouts_last_28_days bigint
)
language sql
stable
as $$
  with w as (select * from public.v_strength_workouts),
       e as (select * from public.v_strength_exercises),
       s as (select * from public.v_strength_sets)
  select
    (select count(*) from w),
    (select count(*) from e),
    (select count(distinct exercise_definition_id) from e),
    (select count(*) from s),
    (select count(*) from s where weight_kg is not null and reps is not null),
    (select count(*) from s where weight_kg is null or reps is null),
    (select sum(volume_kg) from s where weight_kg is not null and reps is not null),
    (select min(local_date) from w),
    (select max(local_date) from w),
    (select count(*) from w where local_date > (select max(local_date) from w) - 28);
$$;

comment on function public.training_overview() is
  'Phase 4 read model. Headline training totals for the signed-in user. Volume counts only sets carrying both a load and a rep count; the rest are reported as non_volume_sets.';

-- ---------------------------------------------------------------------------
-- One row per workout, with its counts. The shape the history list, the
-- recent-activity panel and the workout header all read, so the definition of
-- "a workout's volume" exists once.
-- ---------------------------------------------------------------------------

create or replace function public.training_workout_summaries(
  p_limit  integer default 20,
  p_offset integer default 0,
  p_from   date default null,
  p_to     date default null,
  p_search text default null
)
returns table (
  id              uuid,
  title           text,
  local_date      date,
  start_utc       timestamptz,
  duration_s      integer,
  source_key      text,
  exercise_count  bigint,
  set_count       bigint,
  volume_sets     bigint,
  total_volume_kg numeric,
  total_reps      bigint,
  total_count     bigint
)
language sql
stable
as $$
  with filtered as (
    select w.*
      from public.v_strength_workouts w
     where (p_from is null or w.local_date >= p_from)
       and (p_to is null or w.local_date <= p_to)
       and (
         p_search is null
         or btrim(p_search) = ''
         or w.title ilike '%' || btrim(p_search) || '%'
       )
  ),
  counted as (
    select f.*, count(*) over () as total_count
      from filtered f
     order by f.local_date desc, f.start_utc desc, f.id
     limit greatest(p_limit, 0) offset greatest(p_offset, 0)
  )
  select
    c.id,
    c.title,
    c.local_date,
    c.start_utc,
    c.duration_s,
    c.source_key,
    (select count(*) from public.v_strength_exercises e where e.workout_id = c.id),
    (select count(*) from public.v_strength_sets s
       join public.v_strength_exercises e on e.id = s.exercise_id
      where e.workout_id = c.id),
    (select count(*) from public.v_strength_sets s
       join public.v_strength_exercises e on e.id = s.exercise_id
      where e.workout_id = c.id and s.weight_kg is not null and s.reps is not null),
    (select sum(s.volume_kg) from public.v_strength_sets s
       join public.v_strength_exercises e on e.id = s.exercise_id
      where e.workout_id = c.id and s.weight_kg is not null and s.reps is not null),
    (select sum(s.reps) from public.v_strength_sets s
       join public.v_strength_exercises e on e.id = s.exercise_id
      where e.workout_id = c.id),
    c.total_count
  from counted c
  order by c.local_date desc, c.start_utc desc, c.id;
$$;

comment on function public.training_workout_summaries(integer, integer, date, date, text) is
  'Phase 4 read model. Paginated workout summaries, newest first, with total_count carried on every row so the caller never needs a second count query.';

-- ---------------------------------------------------------------------------
-- Workout detail: the whole hierarchy in one round trip, so the page never
-- issues a query per exercise.
-- ---------------------------------------------------------------------------

create or replace function public.training_workout_detail(p_workout_id uuid)
returns jsonb
language sql
stable
as $$
  select case when w.id is null then null else jsonb_build_object(
    'id',           w.id,
    'title',        w.title,
    'local_date',   w.local_date,
    'start_utc',    w.start_utc,
    'duration_s',   w.duration_s,
    'source_key',   w.source_key,
    'import_id',    w.import_id,
    'exercises',    coalesce((
      select jsonb_agg(x order by x->>'order_index')
        from (
          select jsonb_build_object(
            'id',                     e.id,
            'order_index',            e.order_index,
            'exercise_definition_id', e.exercise_definition_id,
            'display_name',           d.display_name,
            'definition_key',         d.key,
            'name_raw',               e.exercise_name_raw,
            -- Which columns this exercise's sets actually carry, so the UI can
            -- render a load table or a distance table without assuming either.
            'has_load',      bool_or(s.weight_kg is not null),
            'has_reps',      bool_or(s.reps is not null),
            'has_distance',  bool_or(s.distance_m is not null),
            'has_duration',  bool_or(s.duration_s is not null),
            'has_rpe',       bool_or(s.rpe is not null),
            'set_count',     count(s.id),
            'volume_kg',     sum(s.volume_kg) filter (where s.weight_kg is not null and s.reps is not null),
            'top_weight_kg', max(s.weight_kg),
            'sets', coalesce(jsonb_agg(
                      jsonb_build_object(
                        'id',         s.id,
                        'set_number', s.set_number,
                        'set_type',   s.set_type,
                        'weight_kg',  s.weight_kg,
                        'reps',       s.reps,
                        'rpe',        s.rpe,
                        'duration_s', s.duration_s,
                        'distance_m', s.distance_m,
                        'volume_kg',  case when s.weight_kg is not null and s.reps is not null
                                           then s.volume_kg end
                      ) order by s.set_number
                    ) filter (where s.id is not null), '[]'::jsonb)
          ) as x
          from public.v_strength_exercises e
          join public.exercise_definitions d on d.id = e.exercise_definition_id
          left join public.v_strength_sets s on s.exercise_id = e.id
         where e.workout_id = w.id
         group by e.id, e.order_index, e.exercise_definition_id, d.display_name, d.key, e.exercise_name_raw
        ) q
    ), '[]'::jsonb)
  ) end
  from public.v_strength_workouts w
 where w.id = p_workout_id;
$$;

comment on function public.training_workout_detail(uuid) is
  'Phase 4 read model. One workout with its exercises and sets, plus per-exercise has_* flags so the UI renders only the columns the normalized data actually carries.';

-- ---------------------------------------------------------------------------
-- Weekly training frequency and volume, zero-filled across the requested span.
--
-- A week with no workouts is a real, meaningful zero for FREQUENCY: the user
-- did not train. It is NOT a zero for VOLUME, where it means "no observation".
-- The two are returned in one row so a chart can render both honestly.
-- ---------------------------------------------------------------------------

create or replace function public.training_weekly_series(p_weeks integer default 12)
returns table (
  week_start    date,
  workout_count bigint,
  set_count     bigint,
  volume_sets   bigint,
  volume_kg     numeric,
  total_reps    bigint
)
language sql
stable
as $$
  with bounds as (
    select date_trunc('week', coalesce(max(w.local_date), current_date))::date as last_week
      from public.v_strength_workouts w
  ),
  weeks as (
    select generate_series(
             (select last_week from bounds) - ((greatest(p_weeks, 1) - 1) * 7),
             (select last_week from bounds),
             interval '7 days'
           )::date as week_start
  ),
  per_workout as (
    select date_trunc('week', w.local_date)::date as week_start,
           w.id as workout_id
      from public.v_strength_workouts w
  ),
  per_set as (
    select date_trunc('week', w.local_date)::date as week_start,
           s.id, s.weight_kg, s.reps, s.volume_kg
      from public.v_strength_sets s
      join public.v_strength_exercises e on e.id = s.exercise_id
      join public.v_strength_workouts w on w.id = e.workout_id
  )
  select
    weeks.week_start,
    -- Frequency: an honest zero when the user did not train that week.
    coalesce((select count(distinct p.workout_id) from per_workout p where p.week_start = weeks.week_start), 0),
    coalesce((select count(*) from per_set ps where ps.week_start = weeks.week_start), 0),
    coalesce((select count(*) from per_set ps
               where ps.week_start = weeks.week_start
                 and ps.weight_kg is not null and ps.reps is not null), 0),
    -- Volume: NULL when nothing loaded was recorded, so a chart shows a gap
    -- rather than inventing a floor at zero.
    (select sum(ps.volume_kg) from per_set ps
      where ps.week_start = weeks.week_start
        and ps.weight_kg is not null and ps.reps is not null),
    (select sum(ps.reps) from per_set ps where ps.week_start = weeks.week_start)
  from weeks
  order by weeks.week_start;
$$;

comment on function public.training_weekly_series(integer) is
  'Phase 4 read model. ISO weeks over local_date, zero-filled. workout_count is an honest zero for a week without training; volume_kg is NULL when nothing loaded was recorded, so the two are never conflated.';

-- ---------------------------------------------------------------------------
-- Exercise explorer: what the user actually trains, with enough to rank it.
-- ---------------------------------------------------------------------------

create or replace function public.training_exercise_summaries(
  p_limit  integer default 50,
  p_offset integer default 0,
  p_search text default null
)
returns table (
  exercise_definition_id uuid,
  display_name           text,
  definition_key         text,
  session_count          bigint,
  set_count              bigint,
  volume_sets            bigint,
  total_volume_kg        numeric,
  top_weight_kg          numeric,
  total_reps             bigint,
  first_performed        date,
  last_performed         date,
  progression_kind       text,
  total_count            bigint
)
language sql
stable
as $$
  with rows_ as (
    select
      e.exercise_definition_id,
      d.display_name,
      d.key as definition_key,
      count(distinct e.workout_id)                                              as session_count,
      count(s.id)                                                                as set_count,
      count(s.id) filter (where s.weight_kg is not null and s.reps is not null)  as volume_sets,
      sum(s.volume_kg) filter (where s.weight_kg is not null and s.reps is not null) as total_volume_kg,
      max(s.weight_kg)                                                           as top_weight_kg,
      sum(s.reps)                                                                as total_reps,
      min(w.local_date)                                                          as first_performed,
      max(w.local_date)                                                          as last_performed,
      -- What this exercise's data can honestly be compared on. A weighted set
      -- and a distance interval are not on the same scale, so progression must
      -- not put them on the same axis.
      case
        when count(s.id) filter (where s.weight_kg is not null and s.reps is not null) > 0 then 'load'
        when count(s.id) filter (where s.distance_m is not null) > 0                     then 'distance'
        when count(s.id) filter (where s.duration_s is not null) > 0                     then 'duration'
        when count(s.id) filter (where s.reps is not null) > 0                           then 'reps'
        else 'none'
      end as progression_kind
    from public.v_strength_exercises e
    join public.v_strength_workouts w on w.id = e.workout_id
    join public.exercise_definitions d on d.id = e.exercise_definition_id
    left join public.v_strength_sets s on s.exercise_id = e.id
    where p_search is null
       or btrim(p_search) = ''
       or d.display_name ilike '%' || btrim(p_search) || '%'
    group by e.exercise_definition_id, d.display_name, d.key
  )
  select r.*, count(*) over () as total_count
    from rows_ r
   order by r.last_performed desc nulls last, r.session_count desc, r.display_name
   limit greatest(p_limit, 0) offset greatest(p_offset, 0);
$$;

comment on function public.training_exercise_summaries(integer, integer, text) is
  'Phase 4 read model. One row per exercise the user has actually performed, with progression_kind declaring what its data supports being compared on.';

-- ---------------------------------------------------------------------------
-- One exercise by id. Same shape and same rules as the explorer row, so the
-- exercise page and the explorer never disagree about a number.
--
-- This exists rather than filtering the explorer's page client side: a user
-- with more distinct exercises than one page holds would otherwise get a 404
-- for a movement they really perform.
-- ---------------------------------------------------------------------------

create or replace function public.training_exercise_detail(
  p_exercise_definition_id uuid
)
returns table (
  exercise_definition_id uuid,
  display_name           text,
  definition_key         text,
  session_count          bigint,
  set_count              bigint,
  volume_sets            bigint,
  total_volume_kg        numeric,
  top_weight_kg          numeric,
  total_reps             bigint,
  first_performed        date,
  last_performed         date,
  progression_kind       text
)
language sql
stable
as $$
  select
    e.exercise_definition_id,
    d.display_name,
    d.key,
    count(distinct e.workout_id),
    count(s.id),
    count(s.id) filter (where s.weight_kg is not null and s.reps is not null),
    sum(s.volume_kg) filter (where s.weight_kg is not null and s.reps is not null),
    max(s.weight_kg),
    sum(s.reps),
    min(w.local_date),
    max(w.local_date),
    case
      when count(s.id) filter (where s.weight_kg is not null and s.reps is not null) > 0 then 'load'
      when count(s.id) filter (where s.distance_m is not null) > 0                     then 'distance'
      when count(s.id) filter (where s.duration_s is not null) > 0                     then 'duration'
      when count(s.id) filter (where s.reps is not null) > 0                           then 'reps'
      else 'none'
    end
  from public.v_strength_exercises e
  join public.v_strength_workouts w on w.id = e.workout_id
  join public.exercise_definitions d on d.id = e.exercise_definition_id
  left join public.v_strength_sets s on s.exercise_id = e.id
 where e.exercise_definition_id = p_exercise_definition_id
 group by e.exercise_definition_id, d.display_name, d.key;
$$;

comment on function public.training_exercise_detail(uuid) is
  'Phase 4 read model. One exercise the user has performed, in the same shape and by the same rules as a training_exercise_summaries row. Returns no row for an exercise the caller has never performed.';

-- ---------------------------------------------------------------------------
-- Exercise progression: one row per session, with the axis the data supports.
-- ---------------------------------------------------------------------------

create or replace function public.training_exercise_progression(
  p_exercise_definition_id uuid,
  p_limit integer default 60
)
returns table (
  workout_id      uuid,
  workout_title   text,
  local_date      date,
  set_count       bigint,
  volume_sets     bigint,
  total_volume_kg numeric,
  top_weight_kg   numeric,
  total_reps      bigint,
  total_distance_m numeric,
  total_duration_s bigint,
  best_set_reps   integer,
  best_set_weight numeric
)
language sql
stable
as $$
  with sessions as (
    select
      w.id   as workout_id,
      w.title as workout_title,
      w.local_date,
      count(s.id)                                                               as set_count,
      count(s.id) filter (where s.weight_kg is not null and s.reps is not null) as volume_sets,
      sum(s.volume_kg) filter (where s.weight_kg is not null and s.reps is not null) as total_volume_kg,
      max(s.weight_kg)                                                          as top_weight_kg,
      sum(s.reps)                                                               as total_reps,
      sum(s.distance_m)                                                         as total_distance_m,
      sum(s.duration_s)::bigint                                                 as total_duration_s
      from public.v_strength_exercises e
      join public.v_strength_workouts w on w.id = e.workout_id
      left join public.v_strength_sets s on s.exercise_id = e.id
     where e.exercise_definition_id = p_exercise_definition_id
     group by w.id, w.title, w.local_date
  )
  select
    q.workout_id, q.workout_title, q.local_date, q.set_count, q.volume_sets,
    q.total_volume_kg, q.top_weight_kg, q.total_reps, q.total_distance_m, q.total_duration_s,
    -- The heaviest set of the session, and the reps achieved at that load.
    (select s.reps from public.v_strength_sets s
       join public.v_strength_exercises e on e.id = s.exercise_id
      where e.workout_id = q.workout_id
        and e.exercise_definition_id = p_exercise_definition_id
        and s.weight_kg is not null
      order by s.weight_kg desc, s.reps desc nulls last limit 1),
    (select s.weight_kg from public.v_strength_sets s
       join public.v_strength_exercises e on e.id = s.exercise_id
      where e.workout_id = q.workout_id
        and e.exercise_definition_id = p_exercise_definition_id
        and s.weight_kg is not null
      order by s.weight_kg desc, s.reps desc nulls last limit 1)
  from (select * from sessions order by local_date desc limit greatest(p_limit, 1)) q
  order by q.local_date;
$$;

comment on function public.training_exercise_progression(uuid, integer) is
  'Phase 4 read model. One row per session for one exercise, oldest first within the requested window, carrying every axis so the UI can pick the one progression_kind declares valid.';

-- ---------------------------------------------------------------------------
-- Grants.
--
-- PostgreSQL grants EXECUTE on a new function to PUBLIC, so revoking from
-- `anon` alone leaves it callable through the anon key. Every function is
-- therefore revoked from PUBLIC first and granted back only to
-- `authenticated`. RLS would still scope the rows, but an unauthenticated
-- caller has no auth.uid() and must not reach the read model at all.
-- ---------------------------------------------------------------------------

revoke all on function public.training_overview() from public;
revoke all on function public.training_workout_summaries(integer, integer, date, date, text) from public;
revoke all on function public.training_workout_detail(uuid) from public;
revoke all on function public.training_weekly_series(integer) from public;
revoke all on function public.training_exercise_summaries(integer, integer, text) from public;
revoke all on function public.training_exercise_detail(uuid) from public;
revoke all on function public.training_exercise_progression(uuid, integer) from public;

revoke all on function public.training_overview() from anon;
revoke all on function public.training_workout_summaries(integer, integer, date, date, text) from anon;
revoke all on function public.training_workout_detail(uuid) from anon;
revoke all on function public.training_weekly_series(integer) from anon;
revoke all on function public.training_exercise_summaries(integer, integer, text) from anon;
revoke all on function public.training_exercise_detail(uuid) from anon;
revoke all on function public.training_exercise_progression(uuid, integer) from anon;

grant execute on function public.training_overview() to authenticated;
grant execute on function public.training_workout_summaries(integer, integer, date, date, text) to authenticated;
grant execute on function public.training_workout_detail(uuid) to authenticated;
grant execute on function public.training_weekly_series(integer) to authenticated;
grant execute on function public.training_exercise_summaries(integer, integer, text) to authenticated;
grant execute on function public.training_exercise_detail(uuid) to authenticated;
grant execute on function public.training_exercise_progression(uuid, integer) to authenticated;
